<?php

namespace formulas\functions\text;

use Exception;
use formulas\ExpressionNode;
use formulas\functions\AbstractFunction;
use formulas\Typing;

class LowerFunction extends AbstractFunction
{
    protected int $minArguments = 1;
    protected int $maxArguments = 1;

    public function evaluate($scope)
    {
        $this->Expr->checkEvaluationLimits($this);

        $input = $this->arguments[0]->evaluate($scope);

        if (Typing::isNull($input)) {
            return null;
        } elseif (Typing::isString($input)) {
            return mb_strtolower($input);
        } else {
            throw new Exception('fn6 :: lower,' . Typing::getType($input));
        }
    }

    public function toMongoExpression(array $localVariables, array $fieldNames, array $options)
    {
        throw new Exception('This function is not suppoerted in DB yet');

        // Вот этот вариант рабочий, но очень, очень медленный :(
        return [
            '$let' => [
                'vars' => [
                    'input' => $this->arguments[0]->toMongoExpression($localVariables, $fieldNames, $options),
                ],
                'in' => [
                    '$switch' => [
                        'branches' => [[
                            'case' => ['$eq' => ['$$input', null]],
                            'then' => null,
                        ], [
                            'case' => ['$eq' => [['$type' => '$$input'], 'string']],
                            'then' => [
                                '$reduce' => [
                                    'input' => ['$range' => [0, ['$strLenCP' => '$$input']]],
                                    'in' => [
                                        '$concat' => ['$$value', [
                                            '$let' => [
                                                'vars' => [
                                                    'char' => ['$substrCP' => ['$$input', '$$this', 1]]
                                                ],
                                                'in' => [
                                                    '$switch' => [
                                                        'branches' => [
                                                            ['case' => ['$eq' => ['$$char', "\u{0061}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0062}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0063}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0064}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0065}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0066}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0067}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0068}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0069}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{006a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{006b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{006c}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{006d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{006e}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{006f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0070}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0071}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0072}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0073}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0074}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0075}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0076}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0077}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0078}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0079}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{007a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00e0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00e1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00e2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00e3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00e4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00e5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00e6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00e7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00e8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00e9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00ea}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00eb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00ec}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00ed}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00ee}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00ef}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00f0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00f1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00f2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00f3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00f4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00f5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00f6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00f8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00f9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00fa}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00fb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00fc}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00fd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00fe}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{00ff}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0101}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0103}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0105}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0107}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0109}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{010b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{010d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{010f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0111}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0113}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0115}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0117}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0119}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{011b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{011d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{011f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0121}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0123}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0125}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0127}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0129}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{012b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{012d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{012f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0131}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0133}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0135}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0137}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{013a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{013c}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{013e}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0140}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0142}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0144}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0146}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0148}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{014b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{014d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{014f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0151}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0153}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0155}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0157}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0159}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{015b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{015d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{015f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0161}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0163}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0165}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0167}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0169}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{016b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{016d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{016f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0171}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0173}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0175}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0177}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{017a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{017c}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{017e}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0183}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0185}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0188}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{018c}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0192}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0199}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01a1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01a3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01a5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01a8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01ad}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01b0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01b4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01b6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01b9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01bd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01c6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01c9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01cc}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01ce}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01d0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01d2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01d4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01d6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01d8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01da}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01dc}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01df}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01e1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01e3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01e5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01e7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01e9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01eb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01ed}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01ef}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01f3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01f5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01fb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01fd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{01ff}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0201}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0203}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0205}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0207}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0209}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{020b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{020d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{020f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0211}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0213}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0215}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0217}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0253}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0254}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0257}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0258}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0259}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{025b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0260}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0263}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0268}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0269}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{026f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0272}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0275}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0283}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0288}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{028a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{028b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0292}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03ac}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03ad}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03ae}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03af}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03b1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03b2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03b3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03b4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03b5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03b6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03b7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03b8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03b9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03ba}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03bb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03bc}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03bd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03be}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03bf}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03c0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03c1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03c3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03c4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03c5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03c6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03c7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03c8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03c9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03ca}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03cb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03cc}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03cd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03ce}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03e3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03e5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03e7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03e9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03eb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03ed}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{03ef}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0430}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0431}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0432}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0433}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0434}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0435}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0436}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0437}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0438}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0439}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{043a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{043b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{043c}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{043d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{043e}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{043f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0440}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0441}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0442}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0443}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0444}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0445}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0446}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0447}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0448}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0449}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{044a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{044b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{044c}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{044d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{044e}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{044f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0451}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0452}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0453}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0454}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0455}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0456}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0457}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0458}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0459}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{045a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{045b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{045c}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{045e}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{045f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0461}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0463}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0465}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0467}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0469}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{046b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{046d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{046f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0471}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0473}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0475}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0477}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0479}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{047b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{047d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{047f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0481}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0491}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0493}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0495}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0497}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0499}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{049b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{049d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{049f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04a1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04a3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04a5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04a7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04a9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04ab}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04ad}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04af}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04b1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04b3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04b5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04b7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04b9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04bb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04bd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04bf}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04c2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04c4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04c8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04cc}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04d1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04d3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04d5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04d7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04d9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04db}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04dd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04df}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04e1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04e3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04e5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04e7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04e9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04eb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04ef}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04f1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04f3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04f5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{04f9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0561}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0562}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0563}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0564}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0565}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0566}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0567}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0568}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0569}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{056a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{056b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{056c}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{056d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{056e}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{056f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0570}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0571}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0572}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0573}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0574}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0575}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0576}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0577}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0578}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0579}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{057a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{057b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{057c}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{057d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{057e}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{057f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0580}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0581}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0582}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0583}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0584}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0585}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{0586}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10d0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10d1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10d2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10d3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10d4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10d5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10d6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10d7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10d8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10d9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10da}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10db}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10dc}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10dd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10de}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10df}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10e0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10e1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10e2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10e3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10e4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10e5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10e6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10e7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10e8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10e9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10ea}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10eb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10ec}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10ed}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10ee}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10ef}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10f0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10f1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10f2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10f3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10f4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{10f5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e01}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e03}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e05}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e07}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e09}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e0b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e0d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e0f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e11}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e13}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e15}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e17}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e19}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e1b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e1d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e1f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e21}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e23}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e25}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e27}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e29}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e2b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e2d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e2f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e31}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e33}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e35}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e37}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e39}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e3b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e3d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e3f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e41}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e43}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e45}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e47}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e49}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e4b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e4d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e4f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e51}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e53}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e55}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e57}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e59}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e5b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e5d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e5f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e61}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e63}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e65}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e67}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e69}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e6b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e6d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e6f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e71}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e73}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e75}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e77}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e79}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e7b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e7d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e7f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e81}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e83}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e85}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e87}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e89}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e8b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e8d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e8f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e91}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e93}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1e95}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ea1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ea3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ea5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ea7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ea9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1eab}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ead}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1eaf}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1eb1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1eb3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1eb5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1eb7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1eb9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ebb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ebd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ebf}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ec1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ec3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ec5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ec7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ec9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ecb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ecd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ecf}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ed1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ed3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ed5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ed7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ed9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1edb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1edd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1edf}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ee1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ee3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ee5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ee7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ee9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1eeb}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1eed}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1eef}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ef1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ef3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ef5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ef7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1ef9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f00}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f01}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f02}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f03}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f04}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f05}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f06}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f07}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f10}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f11}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f12}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f13}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f14}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f15}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f20}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f21}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f22}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f23}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f24}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f25}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f26}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f27}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f30}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f31}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f32}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f33}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f34}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f35}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f36}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f37}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f40}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f41}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f42}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f43}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f44}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f45}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f51}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f53}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f55}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f57}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f60}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f61}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f62}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f63}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f64}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f65}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f66}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f67}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f80}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f81}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f82}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f83}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f84}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f85}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f86}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f87}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f90}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f91}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f92}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f93}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f94}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f95}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f96}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1f97}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fa0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fa1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fa2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fa3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fa4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fa5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fa6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fa7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fb0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fb1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fd0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fd1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fe0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{1fe1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24d0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24d1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24d2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24d3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24d4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24d5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24d6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24d7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24d8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24d9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24da}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24db}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24dc}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24dd}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24de}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24df}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24e0}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24e1}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24e2}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24e3}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24e4}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24e5}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24e6}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24e7}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24e8}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{24e9}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff41}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff42}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff43}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff44}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff45}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff46}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff47}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff48}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff49}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff4a}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff4b}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff4c}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff4d}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff4e}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff4f}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff50}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff51}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff52}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff53}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff54}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff55}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff56}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff57}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff58}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff59}"]], 'then' => "\u{0041}"],
                                                            ['case' => ['$eq' => ['$$char', "\u{ff5a}"]], 'then' => "\u{0041}"],
                                                        ],
                                                        'default' => '$$char'
                                                    ]
                                                ]
                                            ]
                                        ]]
                                    ],
                                    'initialValue' => '',
                                ]
                            ],
                        ]],
                        'default' => [
                            '$dateFromString' => [
                                'dateString' => '$_this_is_missing',
                                'format' => [[
                                    '$concat' => ['_throw_ lower1,', ['$type' => '$$input']],
                                ]],
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
}